[package]
name = "sunxiboot"
version = "0.1.0"
authors = ["Artur Kowalski <arturkow2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = "3.0.0-beta.2"
byteorder = "1.4.2"
